<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bat.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <Compile Remove="**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BatD\BatD.csproj" />
    <ProjectReference Include="..\BatD.Windows\BatD.Windows.csproj" />
    <ProjectReference Include="..\Subst\Subst.csproj" />
    <ProjectReference Include="..\Tree\Tree.csproj" />
    <ProjectReference Include="..\Cmd\Cmd.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <Compile Include="DosFileSystemTests.cs" />
    <Compile Include="EnvironmentTranslationTests.cs" />
    <Compile Include="PathTranslatorTests.cs" />
    <Compile Include="..\UnitTests\CommandTests.cs" Link="CommandTests.cs" />
    <Compile Include="..\UnitTests\TestCommandContext.cs" Link="TestCommandContext.cs" />
    <Compile Include="..\UnitTests\TestFileSystem.cs" Link="TestFileSystem.cs" />
    <Compile Include="..\UnitTests\TestArgs.cs" Link="TestArgs.cs" />
    <Compile Include="..\UnitTests\SubstTests.cs" Link="SubstTests.cs" />
    <Compile Include="..\UnitTests\ExampleScriptTests.cs" Link="ExampleScriptTests.cs" />
    <Compile Include="..\UnitTests\FileAssociationTests.cs" Link="FileAssociationTests.cs" />
    <Compile Include="..\UnitTests\TreeExclusionTests.cs" Link="TreeExclusionTests.cs" />
    <Compile Include="..\UnitTests\UnixDirDisplayTests.cs" Link="UnixDirDisplayTests.cs" />
    <Compile Include="..\UnitTests\UxFileSystemTests.cs" Link="UxFileSystemTests.cs" />
    <Compile Include="..\UnitTests\TestConsole.cs" Link="TestConsole.cs" />
    <Compile Include="..\UnitTests\TestHarness.cs" Link="TestHarness.cs" />
    <Compile Include="..\UnitTests\ParserExtensions.cs" Link="ParserExtensions.cs" />
    <Compile Include="..\UnitTests\FileSystemExtensions.cs" Link="FileSystemExtensions.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\UnitTests\Examples\**" Link="Examples\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>